version: "3.8"
services:
  backend:
    build: ./back-end
    image: yumyum-backend-image
    container_name: yumyum-backend-container
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - back-end/.env
  frontend:
    build: ./front-end
    image: yumyum-frontend-image
    container_name: yumyum-frontend-container
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - front-end/.env